services:
  - type: web
    name: rylie-seo-hub
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run build && npx prisma generate
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: rylie-seo-hub
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: rylie-seo-hub-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: APP_NAME
        value: "Rylie SEO Hub"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: "https://openrouter.ai/api/v1"
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        value: "https://app.posthog.com"
    autoDeploy: true

databases:
  - name: rylie-seo-hub-db
    databaseName: rylie_seo_hub
    user: rylie_user
    region: oregon

